group: edge
dist: trusty
language: java
jdk: oraclejdk8
script: ./gradlew clean xjc build
before_cache:
  - curl -s https://get.sdkman.io | bash
  - sdk install gradle 3.1
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache.directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
